# Generated by Django 5.0.7 on 2024-07-17 07:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_options_alter_task_due_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='The date and time when this object was created.'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(default='Not available', help_text='Detailed description of the task.', max_length=256),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='The due date and time for completing this task.'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='draft', help_text='Current status of the task.', max_length=16),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(default='Not available', help_text='The title of the task.', max_length=128),
        ),
        migrations.AlterField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='The date and time when this object was last updated.'),
        ),
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.ForeignKey(help_text='The user who owns this task.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
